### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jbbenac** [hbish/delete-old-tweets#2]
Hello,
I have an error running the app.

`Reading tweet.js file
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/ubuntu/delete-old-tweets/index.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`

Do you know how to resolve it?
Thanks in advance
Best

**Comment by hbish** [comment]
@jbbenac thanks for raising this issue.

This is because `deleted.js` is in the wrong format. You can initialize the file with an empty array `[]` to workaround it.

Alternatively, I have fixed the code to correctly initialize the file, so you can pull the latest code and try again. 

The code is not great, since I just wrote it very quickly for my own use. Let me know how you go.

**Comment by hbish** [comment]
@jbbenac I haven't heard back from you for over a month now. I'm pretty sure the issue has been resolved. If you are still having issue feel free to raise another ticket! Thanks!
