### ISSUE TITLE
TypeError: Cannot destructure property 'code' of 'error[0]' as it is undefined.

### ISSUE THREAD

**Issue by Doumham-Armah** [hbish/delete-old-tweets#4]
I tried to run the script but got the following:
`TypeError: Cannot destructure property 'code' of 'error[0]' as it is undefined.
    at /Users/mahmoudhamra/Desktop/tweets/delete-old-tweets-master/index.js:55:17
    at Request._callback (/Users/mahmoudhamra/Desktop/tweets/delete-old-tweets-master/node_modules/twitter/lib/twitter.js:220:14)
    at Request.self.callback (/Users/mahmoudhamra/Desktop/tweets/delete-old-tweets-master/node_modules/request/request.js:185:22)
    at Request.emit (node:events:520:28)
    at Request.<anonymous> (/Users/mahmoudhamra/Desktop/tweets/delete-old-tweets-master/node_modules/request/request.js:1161:10)
    at Request.emit (node:events:520:28)
    at IncomingMessage.<anonymous> (/Users/mahmoudhamra/Desktop/tweets/delete-old-tweets-master/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (node:events:639:28)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)`

**Comment by hbish** [comment]
@Doumham-Armah thanks for raising this github issue! This might be due to the release of the twitter v2 api.

Does your application in Twitter have Elevated access to 1.1 api? You can check in `Projects & Apps` > `Overview`. 

Please let me know, as the script haven't been updated to use the v2 api. 

<img width="771" alt="Screen Shot 2022-08-24 at 21 10 40" src="https://user-images.githubusercontent.com/1014413/186404524-209e40d0-4aae-44ce-a07b-51cfd532df8a.png">

**Comment by Doumham-Armah** [comment]
@hbish just checked, i have both v1.1 and v2 access.

**Comment by Doumham-Armah** [comment]
@hbish I have created a standalone app with v1.1 access only, just like in your case. I am still getting the same error!

**Comment by hbish** [comment]
@Doumham-Armah could you please pull the latest code and run again. I've added a extra print line that should print out the error from Twitter. If you could paste here, that would help me with understanding where the error resides. thanks!

**Comment by Doumham-Armah** [comment]
@hbish my app has read-only access rights. I fixed it. Thanks!

**Comment by hbish** [comment]
Thanks for letting me know! @Doumham-Armah happy purging 😄 

Will close the issue.
